server:
  port: 9002

spring:
  application:
    name: Discount-Service
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_store
    username: root
    password: Ethiopia12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:

      ddl-auto: create-drop

    #      ddl-auto: update
#    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#instance:
#  hostname: localhost